### ISSUE TITLE
auto-entities not loaded properly in Lovelace

### ISSUE THREAD

**Issue by cdeharo** [thomasloven/lovelace-auto-entities#118]
HACS version 1.1.0
Auto-entities version: 16
Home Assistant version 0.110.5
Supervisor 227
HassOS 4.10

Since the last HassOS and HACS update, auto-entities card is not longer loaded properly.

HACS report this repository as `Not loaded`.

When trying to reinstall (or uninstall and install again) I receive the following error in home-assistant.log:
`2020-06-07 22:58:54 WARNING (MainThread) [hacs.repository.plugin.thomasloven.lovelace-auto-entities] 'install' is deprecated, use 'async_install' instead`

In lovelace, it stopped showing the card and showed a red card with the error instead, but since the uninstall/install check it seems to work again.

**Comment by browetd** [comment]
Same issue here... Try to uninstall/re-install same problem but the add-on seems to work...

**Comment by browetd** [comment]
I checked the installation procedure and I still had the "/local/auto-entities.js" as "resources" in configuration.yaml... Replaced with "/hacsfiles/lovelace-auto-entities/auto-entities.js" and it is working fine for me now, the module is loading without error !!!!

**Comment by cdeharo** [comment]
> I checked the installation procedure and I still had the "/local/auto-entities.js" as "resources" in configuration.yaml... Replaced with "/hacsfiles/lovelace-auto-entities/auto-entities.js" and it is working fine for me now, the module is loading without error !!!!

You are right @browetd , the error is fixed changing this:
```yaml
lovelace:
  mode: yaml
  resources:
    - url: /local/community/lovelace-auto-entities/auto-entities.js
      type: module`
```
To this:
```yaml
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
```

But the [HACS documentation](https://hacs.xyz/docs/categories/plugins#custom-view-hacsfiles) states that using the `hacsfiles` path is optional:
> our plugin exists in `www/community/plugin/plugin.js` you can use both `/local/community/plugin/plugin.js` and `/hacsfiles/plugin/plugin.js` to reference it, but only the `hacsfiles` version will have the extra features that HACS offers.

I don't understand the reason why it started showing this error in the recent updates when it worked fine before.

**Comment by browetd** [comment]
@cdeharo agree, maybe a change in the HACS checks/validations (checking now that the file is correctly located even with /local it was still working fine...)... The documentation (repository) indicates still the "/local" file location while when you uninstall and re-install, the last window after installation is indicating the "/hacsfile" file location... Glad it is fixed for you too...

**Comment by thomasloven** [comment]
I believe this was a problem with hacs that has since been fixed.
Is this still an issue?

**Comment by vukisz** [comment]
Hi.

I still have this issue.
My config in /config/ui-lovelace.yaml
```
resources:
#readme https://hacs.xyz/docs/categories/plugins
#Your plugin exists in www/community/plugin/plugin.js you can use both /local/community/plugin/plugin.js and /hacsfiles/plugin/plugin.js to reference it, 
#but only the hacsfiles version will have the extra features that HACS offers.
  - url: hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
    <...>
```
Auto entities works, but Hacs reports: "Not loaded in Lovelace"
Should I move module url to config.yaml?

**Comment by thomasloven** [comment]
Your'e missing the first `/`.

**Comment by vukisz** [comment]
Thanks. Added `/` and it got resolved (after full HA restart)

**Comment by cdeharo** [comment]
It still occurs with HACS 1.2.2

**Comment by geelenbert** [comment]
still looks like an issue.

Addind in resources:
`/local/auto-entities.js`

results in:
Custom element doesn't exist: auto-entities.

changing it to:
`/hacsfiles/lovelace-auto-entities/auto-entities.js`

And now the lovelace card works

**Comment by UnsettlingTrend** [comment]
I installed this first, manually, putting it in the `/config/www/plugins/` directory, but kept getting the `custom element doesn't exist` error.

I think deleted that, and installed using HACS; HACS set up the resource in the dashboard as being in the `/hacsfiles" directory, though that didn't exist. So, I altered the Resource to point to where it actually installed it, in `/config/www/community/`. That also didn't work.

Then I created a symbolic (`ln -s /config/www/community /hacsfiles` from the root directory) and that seemed to do the trick.

**Comment by pgorod** [comment]
I also created the link, but after a reboot it is gone. 

Still, all cards seem to load fine except gallery-card which says `custom element doesn't exist: gallery-card`

This is quite strange, since their configs use the link that is not there...

```
lovelace:
  mode: yaml
  resources:
    # hacsfiles virtual folder points to config/www/community
    - url: /hacsfiles/gallery-card/gallery-card.js?v=3.5.1
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/lovelace-card-templater/lovelace-card-templater.js?v=0.0.17
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/powertodoist-card/powertodoist-card.js?v=0.2
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/sip-hass-card/sipjs-card.js
      type: module
    - url: /hacsfiles/lovelace-template-entity-row/template-entity-row.js
      type: module
    - url: /hacsfiles/history-explorer-card/history-explorer-card.js
      type: module
    - url: /hacsfiles/circular-timer-card/circular-timer-card.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
```

Can anyone explain this?
